### ISSUE TITLE
Feature: add functionality to refresh gallery after deleting items

### ISSUE THREAD

**Issue by pavanjoshi914** [ukieTux/media_scanner#1]
Currently plugin only handles refresh after something is added and not if something is deleted

**Comment by ukieTux** [comment]
Have you tried the same function when you add a new Photo/Video?

`MediaScanner.loadMedia(path: "delete_file_path");`

**Comment by Lzyct** [comment]
> Currently plugin only handles refresh after something is added and not if something is deleted

Have you tried the same function when you add a new Photo/Video?

`MediaScanner.loadMedia(path: "delete_file_path");`

**Comment by pavanjoshi914** [comment]
> > Currently plugin only handles refresh after something is added and not if something is deleted
> 
> Have you tried the same function when you add a new Photo/Video?
> 
> `MediaScanner.loadMedia(path: "delete_file_path");`

Yeah, It's working! thanks!
